### ISSUE TITLE
g-cpan doesn't work without PORTDIR_OVERLAY (using repos.conf)

### ISSUE THREAD

**Issue by tecknicaltom** [gentoo-perl/g-cpan#26]
Portage has deprecated the use of PORTDIR_OVERLAY in favor of the repos.conf method of configuring overlays. g-cpan doens't seem to handle this change.

```
# g-cpan -l 2>/dev/null
 * The option you have chosen isn't supported without a configured overlay.
```

**Comment by bor** [comment]
Related https://bugs.gentoo.org/show_bug.cgi?id=581490

**Comment by marcelser** [comment]
Hi Bor. This bug was reported on 13. Dec 15 so nearly a year ago. Can you please fix this as I don't know how to use g-cpan while this is still not fixed. What variables would I have to set. The manual says GCPAN_OVERLAY which I did but it still fails. Plus what needs to be the content? the directory or just the name as defined in the repos.conf?

**Comment by bor** [comment]
This is in a process.
To ensure there is a need to setup such variables:
```bash
PORTDIR="/usr/portage"
PORTDIR_OVERLAY="/usr/local/portage"
GCPAN_OVERLAY="/usr/local/portage"
```

**Comment by bor** [comment]
Guys please check last git revision. Is it works for you now?
By `emerge -av =app-portage/g-cpan-9999`
